# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Metropolis sampler using Rcpp
#' 
#' @description A Metropolis sampler using Rcpp
#' 
#' @param x0 the initial point of the series
#' @param sigma the standard deviation
#' @param N the sample size
#' 
#' @return a random sample of size \code{N}
#' 
#' @examples
#' \dontrun{
#' x0 = 0;
#' sigma = 2;
#' N = 1000;
#' x = Metropolis(x0, sigma, N)
#' }
#' 
#' @export
Metropolis <- function(x0, sigma, N) {
    .Call('_StatComp20020_Metropolis', PACKAGE = 'StatComp20020', x0, sigma, N)
}

